# Generated by Django 2.2.4 on 2021-02-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_university_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMapURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'verbose_name_plural': "SitemapUrl's",
            },
        ),
    ]
