# Generated by Django 2.2.4 on 2021-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sitemapurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemapurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitemapurl',
            name='url',
            field=models.CharField(help_text='URL example "/s?uni=punjabi-university&cou=btech"', max_length=1000, unique=True),
        ),
    ]
