# Generated by Django 2.2.4 on 2021-02-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210226_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
