# Generated by Django 2.2.4 on 2020-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpapersuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xpapersuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
