# Generated by Django 2.2.4 on 2021-07-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_post_is_verified'),
        ('xpauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpapersuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard.Branch'),
        ),
        migrations.AddField(
            model_name='xpapersuser',
            name='collage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard.Collage'),
        ),
        migrations.AddField(
            model_name='xpapersuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard.Course'),
        ),
        migrations.AddField(
            model_name='xpapersuser',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard.University'),
        ),
    ]
