# Generated by Django 2.2.4 on 2021-07-09 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xpauth', '0002_auto_20210708_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpapersuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.Branch'),
        ),
        migrations.AlterField(
            model_name='xpapersuser',
            name='collage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.Collage'),
        ),
        migrations.AlterField(
            model_name='xpapersuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.Course'),
        ),
        migrations.AlterField(
            model_name='xpapersuser',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.University'),
        ),
    ]
