# Generated by Django 2.2.4 on 2021-07-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpauth', '0003_auto_20210709_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpapersuser',
            name='is_username_varified',
            field=models.BooleanField(default=False),
        ),
    ]
